### ISSUE TITLE
How does this work with 'Current auto delete watched videos'?

### ISSUE THREAD

**Issue by davralin** [tubearchivist/jellyfin#1]
I have it so TA deletes the videos I have watched after a day. Is there any integration with that for jellyfin, or is that something that's only for TA-website?

**Comment by PhuriousGeorge** [comment]
Joining in since I had a similar question when reviewing the code.  Watch status doesn't look like it's passed?

**Comment by bbilly1** [comment]
This is a one way sync, from TA to JF. So you'll still have to mark videos as watched on TA to be deleted automatically. 

I've added some clarification to the readme.
