### ISSUE TITLE
No videos found in Jellyfin

### ISSUE THREAD

**Issue by V3c7r0n** [tubearchivist/jellyfin#15]
When trying to run the metadata update, no series are found. The query on line 48 of series.py returns no results:

 path: str = f"Items?Recursive=true&IncludeItemTypes=Series&fields=ParentId,Path&ParentId={self.yt_collection}"  # noqa: E501

I edited the file to print the return of the query and it shows:

{'Items': [], 'TotalRecordCount': 0, 'StartIndex': 0}

To do this, I edited line #50 to say print(all_shows)

I have also tried modifying the query to remove the IncludeItemTypes filter to:

 path: str = f"Items?Recursive=true&fields=ParentId,Path&ParentId={self.yt_collection}"  # noqa: E501

But that also does not work, producing the same result. I would have expected this to return everything within the container

In Jellyfin, if I look inside the YouTube collection, I see individual folders with the generated strings that match TubeArchivist. 

Jellyfin Version: 10.8.11, hosted on Windows
TubeArchivist & TubeArchivist-jf share the same volume, TubeArchivist-jf has the volume mounted as read-only
Jellyfin server has the same folder mapped as network drive, with read-only permissions

The full console output of running "python main.py" from the app folder of the container is:

[connection] verified jellyfin connection
[connection] verified tube archivist connection
4b628b16745d06ff53a9e28c4c33ab4f <- Note: this is a debug print I added to output the collection ID to the console
Items?Recursive=true&ParentId=4b628b16745d06ff53a9e28c4c33ab4f <- Note: This is a debug print I added to output the query to the Jellyfin API
{'Items': [], 'TotalRecordCount': 0, 'StartIndex': 0} <- Note: This is the debug print I added to print out the results, as mentioned previously
waiting for library refresh
waiting for library refresh
waiting for library refresh

**Comment by V3c7r0n** [comment]
Also of note, the media refresh within Jellyfin is triggered when this is run, so it is connecting to the Jellyfin API and issuing commands.

In addition, printing the response.json() for the Jellyfin connection (added a print statement on line 28 of connect.py) it does return data, however it always seems to return the same data, regardless of the query being presented. After parsing this output, it also does not seem to be getting the correct ID for the YouTube collection from within Jellyfin, though I have yet to determine why.

**Comment by bbilly1** [comment]
You can browse the API directly to reconstruct that from here:
https://github.com/tubearchivist/tubearchivist-jf/blob/master/app/src/series.py#L21-L29

```
/Items?Recursive=true&includeItemTypes=Folder&api_key=<yourkey>
```

This will return all folders. Then grab the `Id` key. While this will get all items from that folder:
```
/Items?Recursive=true&IncludeItemTypes=Series&fields=ParentId,Path&ParentId=<folderid>&api_key=<yourkey>
```

What I could see, maybe you have more than one folder called "YouTube"?

**Comment by V3c7r0n** [comment]
Thanks, I hadn't had a chance to update this yet. I did indeed have a YouTube folder under another library.  Overall after manually assigning the library ID it does seem to be working - except for having one channel it didn't rename, but I'm not sure why yet.

Perhaps a note in the documentation may help prevent that from happening to others?

**Comment by bbilly1** [comment]
sounds good.
