### ISSUE TITLE
Script does not do anything

### ISSUE THREAD

**Issue by CommanderRedYT** [tubearchivist/jellyfin#19]
My setup is 90% the same (with the exception of jellyfin running outside of docker). When I run the manual start function, the script prints few things, but my library remains completely the same.

The titles are not changed, no thumbnails are there, the only thing that is visible is the youtube video description.

**Comment by bbilly1** [comment]
Maybe some of these days we can all reunite under a tree in nature somewhere, can all come to an understanding that we don't have magic, no clairvoyant abilities, no way and no will to guess what you could possibly see in the logs. Some day.

**Comment by CommanderRedYT** [comment]
![grafik](https://github.com/tubearchivist/tubearchivist-jf/assets/43087936/4e5b399f-3783-4f3d-bc85-cbe619a629b6)
![grafik](https://github.com/tubearchivist/tubearchivist-jf/assets/43087936/ff297800-98d4-410f-9ac0-76ae813dfba7)

Maybe some of these days we can get actual log output (for example, the "Found Folder" is something I had to patch because this wonderful tool did not have enough logging)

**Comment by bbilly1** [comment]
There is not enough info to do anything here. You probably want to stick with the documented docker compose setup.

**Comment by CommanderRedYT** [comment]
Okay, I will rewrite all of this, having a media server inside docker is a no-go, especially with a setup that already exists.

**Comment by bbilly1** [comment]
None the less, this integration is tested functions as documented, not necessarily as you have your things setup. If you want to help improve this to make this compatible with other setups, please make a PR with your changes.

**Comment by CommanderRedYT** [comment]
While debugging, I found that https://github.com/tubearchivist/tubearchivist-jf/blob/master/app/src/series.py#L51 returns a empty array. When I looked at the ID in the query, it looked different than the ID returned in the constructor. I will now trace back why this is the case.

**Comment by CommanderRedYT** [comment]
I have traced this issue back to that my folder on my physical disk is not called "YouTube", but "TubeArchivist". I have another YouTube folder for my previous YouTube download setup. I will make a PR for having a custom folder name

**Comment by bbilly1** [comment]
Good to hear you found it. No need to make this configurable, that just add unneeded complexity. Just name it as documented and you should be good.

**Comment by CommanderRedYT** [comment]
I made a PR, because renaming is not a option for me as too many things depend on the name. I am sure that I am not the only one. PR: https://github.com/tubearchivist/tubearchivist-jf/pull/20
