### ISSUE TITLE
Update Played in TA when played in Jellyfin

### ISSUE THREAD

**Issue by stevenhorner** [tubearchivist/jellyfin#22]
**Request**
I know you clearly state this is a one way sync from TubeArchivist (TA) to Jellyfin but would you consider adding the ability to update the played status in TA when played in Jellyfin.

It appears others have mentioned this but not requested it [here](https://github.com/tubearchivist/tubearchivist-jf/issues/1) for instance.

This would then allow the ability to configure TA to autodelete the videos when played without having to then manually mark them as watched in TA, which can be a pain if you watch a lot of TA downloaded videos. This obviously has some limitations if you have a multiuser setup in Jellyfin and want each person to be able to watch the downloaded YouTube videos but then in that scenario you just don't autodelete the file in TA.

Thanks

**Comment by bbilly1** [comment]
I'd be happy to look at a PR to further extend the functionality of this integration.

**Comment by stevenhorner** [comment]
Not a python programmer but will spend a bit more time with Tube Archivist then see if I can figure out updating the tubearchivist-jf code. The code didn't look too complicated, but have you got any pointers to help me along with trying to add this?

**Comment by bbilly1** [comment]
This repo will not receive any future updates. Future development will be focused on the plugin: https://github.com/tubearchivist/tubearchivist-jf-plugin
