### ISSUE TITLE
a repo support emby edit base on tubearchivist-jf

### ISSUE THREAD

**Issue by xinmans** [tubearchivist/jellyfin#24]
https://github.com/xinmans/tubearchivist-emby

**Comment by bbilly1** [comment]
what were the changes needed? Please keep it as a fork from this main repo so we can see if that would be suitable to support both media servers from the same project or if that should better stay in a separate repo.

**Comment by xinmans** [comment]
> what were the changes needed? Please keep it as a fork from this main repo so we can see if that would be suitable to support both media servers from the same project or if that should better stay in a separate repo.

i will try

**Comment by xinmans** [comment]
> what were the changes needed? Please keep it as a fork from this main repo so we can see if that would be suitable to support both media servers from the same project or if that should better stay in a separate repo.

i have edit some code to support emby， and add logging to debug. can't merge to jf repo to both support emby and jeffylin
