### ISSUE TITLE
youtube playlist support

### ISSUE THREAD

**Issue by ghaflims** [tubearchivist/jellyfin#25]
Greetings,, thank you for your amazing work which I came cross while searching for jellyfin tubearchivist support...
is it possible to add a feature to support youtube playlist as this will be a huge game changer as most of the videos are organized in playlist now..
Regards..

**Comment by bbilly1** [comment]
Playlists in JF work very differently as in TA and by extension YT, as playlists are tied to channels. You could easily have a too big amount of playlists to be usable in JF. Plus you also don't have a way to separate playlists from TA with other playlists you create in JF. 

With that in mind, I don't see how this could be implemented without severe limitations.

Closing this as won't fix for now.
