### ISSUE TITLE
Does this work with Emby?

### ISSUE THREAD

**Issue by janaxhell** [tubearchivist/jellyfin#3]
I've done exactly as explained in Home, but for Emby.
I have now a Youtube library full of channels each of which contains a Season Unknown inside which there are videos with TubeArchivist style title. No image or metadata of sort. 
I've checked if there was an API to setup, but TA only shows its own one and Emby can only create a custom one that I cannot add to TA.

![image](https://user-images.githubusercontent.com/55061479/235310029-c6c511ce-6923-4d3b-b298-c7961215e912.png)

![vivaldi_g4i4Z53mRn](https://user-images.githubusercontent.com/55061479/235309864-31a0a345-bb04-43ae-bbbc-3b31491ecb1e.png)

**Comment by bbilly1** [comment]
thanks for testing this out. this is a jellyfin integration, if you want to make it work for emby, please contribute.

**Comment by janaxhell** [comment]
I'm not a coder, I'm just testing it out of curiosity..
