### ISSUE TITLE
Temporary season folders not detected

### ISSUE THREAD

**Issue by jonvmey** [tubearchivist/jellyfin#30]
When syncing the process gets stuck waiting for temporary season directories. The folders are created and visible from Jellyfin but for some reason they're missing the `indexNumber` field that the check is looking for. This causes the season creation check to get stuck and eventually time out.

I managed to work around this by falling back to looking for a directory with the same name as the expected value when `indexNumber` does not exist. I can PR this change if desired.

**Comment by bbilly1** [comment]
Switch to the plugin: https://github.com/tubearchivist/tubearchivist-jf-plugin

That should handle that better.
