### ISSUE TITLE
Scripts are timeouting all the time

### ISSUE THREAD

**Issue by CommanderRedYT** [tubearchivist/jellyfin#32]
When waiting for jellyfin to finish scanning, the script usually times out.

I only have about ~2TB of data in Tubearchivist. This takes jellyfin quite some time tho to go through. The 12*5 seconds waiting is way too low, it usually takes 3 minutes or more. I was not able to successfully sync with this script.

**Comment by Iliannnn** [comment]
Have you tried the [Jellyfin TubeArchivist Plugin](https://github.com/DarkFighterLuke/TubeArchivistMetadata/) yet? It integrates fully with Jellyfin as a plugin and not just with an API integration, this might fix your issues.

**Comment by CommanderRedYT** [comment]
@Iliannnn 
No I haven't, but thanks for pointing it out, did not know that existed! And it works without patches!

**Comment by jvtrigueros** [comment]
I was also having the timeout issue, and ran the code line by line and found it was looking up the series `IndexNumber` rather than the season `Name`. https://github.com/tubearchivist/tubearchivist-jf/blob/master/app/src/series.py#L228

I changed that line to:
```python
return [str(i.get("Name")) for i in all_seasons["Items"]]
```

**Comment by CommanderRedYT** [comment]
@jvtrigueros I also tried that, but it did not seem to work for me. Maybe because there was already metadata? Anyways, I moved on to the Jellyfin Plugin and just loving it!

**Comment by jvtrigueros** [comment]
@CommanderRedYT I would've liked to use the plugin but I kept seeing Authorization error in the Jellyfin logs and had no easy way to debug :/

**Comment by bbilly1** [comment]
The plugin is now in the main organization. Switch to that if you have problems with that.
