### ISSUE TITLE
Possible to add a "Folder Ignore" feature to the script?

### ISSUE THREAD

**Issue by Gaffers2277** [tubearchivist/jellyfin#7]
Been trying out the script and its great. Works well and all, but i have some Youtube channels where i have off site videos from Patreon and such that i  want in the Youtube channels series folder under the "Specials" folder but it seems to break the script. I assume as the videos are not in Tube Archivist. I don't know how to code so i was wondering if it would be possible to add a folder ignore feature to skip specified folder like "Specials"?

**Comment by bbilly1** [comment]
that is not a supported TA setup, there is no flexibility on the filesystem level. so sooner or later, your setup is going to break.

I highly suggest to stick to the application default there.

**Comment by Gaffers2277** [comment]
Well i added a ignore function that looks at Jellyfin seasons called "Seasons" and folders named "Seasons" or "Extras" in a ignore.txt file and tells the script to ignore these. It's been working for 2 days now with no problems so far. If it breaks i'll look into a different way of having off site videos like patreon exclusives sorted with the Youtube Channels
