### ISSUE TITLE
Possible to show Playlists as 'seasons'?

### ISSUE THREAD

**Issue by HStep20** [tubearchivist/jellyfin#9]
With how rigid TubeArchivist is when it comes to the folder structure, Im not sure this is even possible, but it would be great to have the plugin read Playlists from a channel as 'seasons' if only playlists are archived. 

Oftentimes, I will select a series of playlists from a channel and download those only. Since the cohesive nature of a playlist lends itself towards being a 'season' of a show, it makes sense if the playlists showed up as individual seasons under a channel "show". I'm not sure if there is a way to differentiate which items are part of a playlist within the filesystem/api the plugin uses to get info from TA, but it would be amazing for playlists to show up as Seasons within JF

**Comment by bbilly1** [comment]
that wouldn't be possible. in jellyfin seasons are a number and not a string like the playlist title. additionally a video can be in multiple playlists at the same time but not in multiple seasons.

that is a good example why having the flexibility of TA is beneficial to accommodate the Metadata structure from YouTube.
